openapi: "3.0.3"
info:
  title: DigiVine API
  description: REST/CRUD API for the Digivine data warehouse
  version: "0.3"
  contact:
    name: DigiVine
    url: https://www.digivine.org/
    email: info@digivine.org
servers:
  - url: http://127.0.0.1/api/v0.3
externalDocs:
  description: RFC7946 - The GeoJSON format.
  url: https://tools.ietf.org/html/rfc7946

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api-token
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  links:
    $ref: "./links/_index.yaml"

security:
  - ApiKeyAuth: []

tags:
  $ref: "./tags/_index.yaml"

paths:
  /climate:
    $ref: "path/climate_index.yaml"
  /climate/{ClimateId}:
    $ref: "path/climate.yaml"
  /forecast:
    $ref: "path/forecast_index.yaml"
  /forecast/{ForecastId}:
    $ref: "path/forecast.yaml"
  /field:
    $ref: "path/field_index.yaml"
  /field/{FieldId}:
    $ref: "path/field.yaml"
  /field/{FieldId}/planter:
    $ref: "path/planter_index.yaml"
  /field/{FieldId}/planter/{PlanterRunId}:
    $ref: "path/planter.yaml"
  /field/{FieldId}/planter/{PlanterRunId}/plant:
    $ref: "path/plant_index.yaml"
  /field/{FieldId}/planter/{PlanterRunId}/plant/{PlantId}:
    $ref: "path/plant.yaml"
  /field/{FieldId}/planter/{PlanterRunId}/plant/{PlantId}/quality_measurement:
    $ref: "path/quality_measurement_index.yaml"
  /field/{FieldId}/planter/{PlanterRunId}/plant/{PlantId}/quality_measurement/{QualityMeasurementId}:
    $ref: "path/quality_measurement.yaml"
  /terrain:
    $ref: "path/terrain_index.yaml"
  /terrain/{TerrainId}:
    $ref: "path/terrain.yaml"
  /harvest/task:
    $ref: "path/harvest_task_index.yaml"
  /harvest/task/{HarvestTaskId}:
    $ref: "path/harvest_task.yaml"
  /harvest/complete:
    $ref: "path/harvest_complete_index.yaml"
  /harvest/complete/{HarvestTaskId}:
    $ref: "path/harvest_complete.yaml"
  /spray/task:
    $ref: "path/spray_task_index.yaml"
  /spray/task/{SprayTaskId}:
    $ref: "path/spray_task.yaml"
  /spray/complete:
    $ref: "path/spray_complete_index.yaml"
  /spray/complete/{SprayTaskId}:
    $ref: "path/spray_complete.yaml"
