name: Check Bundle 

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout spec
        uses: actions/checkout@v3
      - name: bundle spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle --outfile bundled/openapi.yml -t yaml openapi.yaml"
      - name: push specification
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bundled/openapi.yml
          git commit -m "Bundle Specification"
          git push
