name: Check Bundle 

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout spec
        uses: actions/checkout@v2
      - name: bundle spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle --outfile bundled/tmp.yml -t yaml openapi.yaml"
      - name: Run OpenAPI Diff
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: bundled/tmp.yml
          base-spec: bundled/openapi.yaml
