name: Specification Diff

on: [pull_request]

jobs:
  openapi-compatiable:
    strategy:
      max-parallel: 1
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out HEAD revision
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out BASE revision
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: bundle spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle --outfile tmp.yml -t yaml head/openapi.yaml"
      - name: Run OpenAPI Diff (from HEAD revision)
        uses: LimeFlight/openapi-diff-action@master
        with:
          head_spec: tmp.yml
          base_spec: base/bundled/openapi.yaml
          output_path: ./output
          github_token: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: diff-reports
          path: ./output